<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-3R6COPU" failures="1" tests="5" name="Surefire test" time="40.356" errors="0" timestamp="2025-02-09T18:56:03 CST">
  <testcase classname="automatedProject.tests.ErrorValidationsTest" name="LoginErrorValidation" time="0.526"/>
  <testcase classname="automatedProject.tests.ErrorValidationsTest" name="ProductErrorValidation" time="2.926">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at automatedProject.tests.ErrorValidationsTest.ProductErrorValidation(ErrorValidationsTest.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- ProductErrorValidation -->
  <testcase classname="automatedProject.tests.SubmitOrderTest" name="submitOrder" time="3.848"/>
  <testcase classname="automatedProject.tests.SubmitOrderTest" name="submitOrder" time="3.794"/>
  <testcase classname="automatedProject.tests.SubmitOrderTest" name="OrderHistoryTest" time="0.935"/>
</testsuite> <!-- Surefire test -->
